[package]
name = "iota_sc_utils"
version = "0.1.0"
authors = ["Th3B0Y <brunoamancio.ti@gmail.com>"]
edition = "2018"

[dependencies]
wasmlib = { path = "../wasp/contracts/rust/wasmlib" }
iota-sc-hname-generator = "1.1.1"