[package]
name = "iota_sc_utils"
version = "0.2.0"
authors = ["Th3B0Y <constantlychanging@pm.me>"]
edition = "2018"

[dependencies]
wasmlib = { path = "../wasp/contracts/rust/wasmlib" }
iota-sc-hname-generator = "1.1.1"